# Generated by Django 3.2.17 on 2023-02-13 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospede', '0002_auto_20230212_1256'),
        ('acomodacao', '0003_auto_20230213_1548'),
        ('plataforma', '0002_auto_20230212_1256'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_inicio', models.DateField()),
                ('dt_fim', models.DateField()),
                ('slug', models.SlugField()),
                ('dt_cadastro', models.DateTimeField(auto_now=True)),
                ('dt_update', models.DateTimeField(auto_now=True)),
                ('acomodacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acomodacao.acomodacao')),
                ('cadastrado_por', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('comissao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.comissao')),
                ('hospede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospede.hospede')),
                ('plataforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.plataforma')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserva.status')),
            ],
        ),
    ]
