# Generated by Django 3.2.17 on 2023-02-12 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comissao', models.FloatField()),
                ('dt_inicio', models.DateField()),
                ('dt_fim', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da plataforma:')),
                ('mensalidade', models.FloatField(blank=True, null=True)),
                ('comissao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plataforma.comissao')),
            ],
        ),
    ]
