# Generated by Django 3.2.17 on 2023-02-12 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plataforma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plataforma',
            name='cadastrado_por',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plataforma',
            name='dt_cadastro',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='plataforma',
            name='dt_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='plataforma',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
