# Generated by Django 3.2.17 on 2023-02-20 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0002_auto_20230212_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plataforma',
            name='comissao',
        ),
        migrations.AddField(
            model_name='comissao',
            name='plataforma',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='plataforma.plataforma'),
            preserve_default=False,
        ),
    ]
