# Generated by Django 3.2.17 on 2023-02-20 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acomodacao', '0003_auto_20230213_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='acomodacao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='acomodacao.acomodacao'),
            preserve_default=False,
        ),
    ]
